name: ci-deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - main

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [16]
        deploy-dir: [.output/public]
        deploy-user: [sanhvvt]
        deploy-repo: [sanhvvt.github.io]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Generate
        env:
          # BASE: /
          # NUXT_APP_BASE_URL: /${{ matrix.deploy-repo }}/
          # HOSTNAME: https://sanhvvt.github.io/
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm generate

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          # repo: ${{ matrix.deploy-user }}/${{ matrix.deploy-repo }}
          target_branch: gh-pages
          build_dir: ${{ matrix.deploy-dir }}
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GH }}
